INSERT INTO CUSTOMER (CUSTOMER_ID,NAME,USERNAME,TYPE,BUSINESS_VOLUME_DISCOUNT,BUSINESS_PARTNER,BUSINESS_DESCRIPTION,addressLine1,addressLine2,city,country,state,zip) VALUES (1,'Business Test User','btuser','BUSINESS','Y','N','Test business customer for database validation','500 Main Street','Suite 200','Raleigh','USA','NC','27601') ON CONFLICT (CUSTOMER_ID) DO NOTHING;
INSERT INTO CUSTOMER (CUSTOMER_ID,NAME,USERNAME,TYPE,RESIDENTIAL_HOUSEHOLD_SIZE,RESIDENTIAL_FREQUENT_CUSTOMER,addressLine1,addressLine2,city,country,state,zip) VALUES (2,'Residential Test User','rtuser','RESIDENTIAL',4,'Y','123 Main Street','Apt 5B','New York','USA','NY','10001') ON CONFLICT (CUSTOMER_ID) DO NOTHING;
INSERT INTO SUPPLIER (SUPP_ID,NAME) VALUES (1,'DEPOT1') ON CONFLICT DO NOTHING;
INSERT INTO SUPPLIER (SUPP_ID,NAME) VALUES (2,'DEPOT2') ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (CAT_ID,CAT_NAME,PARENT_CAT) VALUES (1,'Electronics',NULL) ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (CAT_ID,CAT_NAME,PARENT_CAT) VALUES (2,'Movies',NULL) ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (CAT_ID,CAT_NAME,PARENT_CAT) VALUES (3,'Computers',1) ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (CAT_ID,CAT_NAME,PARENT_CAT) VALUES (4,'Phones',1) ON CONFLICT DO NOTHING;